```{r}
#| label: import packages

library(tidyverse)
library(readr)
library(summarytools)
library(gtsummary)
library(modelsummary)
library(janitor)
library(treemap)
library(esquisse)
library(kableExtra)
library(flextable)
library(officer)
library(knitr)
library(rmarkdown)
library(patchwork)
library(easystats)
```

```{r}
#| label: import and transform data (df_insones_medicados)

df <- read_csv("data/df.csv")


df_insones <- df |> 
  filter(insone == 1) |> 
  rename(toma_remedio_tr = medicacao___0) |>
  mutate(
    sexo_tr = case_when(
      sexo == 1 ~ "Feminino",
      sexo == 2 ~ "Masculino"),
    escolaridade_tr = case_when(
      escolaridade <= 8 ~ "Nao Superior",
      escolaridade >= 9 ~ "Superior"),
    estado_civil_tr = case_when(
      estado_civil <= 2 ~ "Married/United",
      estado_civil >= 3 ~ "Single/Divorced"),
    randomizacao_tr = case_when(
      randomizacao == 1 ~ "ACT",
      randomizacao == 2 ~ "CBT",
      randomizacao == 3 ~ "WL"),
    etnia_tr = case_when(
      etnia == 1 ~ "Branco",
      etnia >= 2 ~ "Pretos e Pardos"),
    atividade_fisica_tr = case_when(
      atividade_fisica <= 1 ~ "Sedentário (<2x/semana)",
      atividade_fisica >= 2 ~ "Ativo (≥2x/semana)",
    )) |>
  mutate(medicacao_semana_tr = case_when(
    medicacao_semana == 0 ~ "Não toma",
    medicacao_semana <= 5 ~ "Uso Ocasional (1-5 dias)",
    medicacao_semana >= 6 ~ "Uso Contínuo (6-7 dias)"
    )) |> 
    # Juntar Uso Ocasional e Uso Contínuo
  mutate(uso_naouso = case_when(
    medicacao_semana == 0 ~ "Não Usa",
    medicacao_semana >= 1 ~ "Usa")) |> 
  mutate(classe_medicacao = case_when(
    medicacao___1 == 1 ~ "Benzodiazepínico",
    medicacao___2 == 1 ~ "Benzodiazepínico",
    medicacao___3 == 1 ~ "Benzodiazepínico",
    medicacao___4 == 1 ~ "Benzodiazepínico",
    medicacao___5 == 1 ~ "Drogas Z",
    medicacao___6 == 1 ~ "Drogas Z",
    medicacao___7 == 1 ~ "Antidepressivos sedativos",
    medicacao___8 == 1 ~ "Antidepressivos sedativos",
    medicacao___9 == 1 ~ "Antidepressivos sedativos",
    medicacao___10 == 1 ~ "Anticonvulsivantes",
    medicacao___11 == 1 ~ "Anticonvulsivantes",
    medicacao___12 == 1 ~ "Antidepressivos sedativos",
    medicacao___13 == 1 ~ "Antipsicóticos",
    medicacao___14 == 1 ~ "Antipsicóticos",
    medicacao___15 == 1 ~ "Agonista do receptor de melatonina",
    medicacao___16 == 1 ~ "Agonista do receptor de melatonina",
    medicacao___17 == 1 ~ "Sem Receita",
    medicacao___18 == 1 ~ "Sem Receita",
    medicacao___19 == 1 ~"Sem Receita")) |> 
  mutate(across(ends_with("tr"), as_factor)) |> 
  mutate(medicacao_semana_tr = fct_relevel(medicacao_semana_tr, c("Não toma", "Uso Ocasional (1-5 dias)", "Uso Contínuo (6-7 dias)")))

df_insones |> 
  dfSummary(round.digits = 2) |> stview()
```

Quem é esse povo que diz que não toma medicamentos? O problema parece ser que eles marcaram na variável `medicacao___` qualquer medicamentos que eles tomaram em algum momento da vida, não sabemos nem se relacionado a insônia.

```{r}
df_insones |> 
  filter(medicacao_semana_tr == "Não toma") |> 
  dfSummary(round.digits = 2) |> 
  stview()
```

```{r}
#| label: creating long_df e sum_df
long_df <- df_insones |> 
  pivot_longer(
    cols = starts_with("medicacao___"),
    names_to = "medicacao",
    values_to = "taken") |> 
  mutate(medicacao = case_when(
    medicacao == "medicacao___1" ~ "Alprazolam",
    medicacao == "medicacao___2" ~  "Bromazepam",
    medicacao == "medicacao___3" ~ "Clonazepam",
    medicacao == "medicacao___4" ~ "Diazepam",
    medicacao == "medicacao___5" ~ "Zolpidem",
    medicacao == "medicacao___6" ~ "Eszopiclona",
    medicacao == "medicacao___7" ~ "Amitriptilina",
    medicacao == "medicacao___8" ~ "Doxepina",
    medicacao == "medicacao___9" ~ "Trazodona",
    medicacao == "medicacao___10" ~ "Gabapentina",
    medicacao == "medicacao___11" ~  "Pregabalina",
    medicacao == "medicacao___12" ~  "Mirtazapina",
    medicacao == "medicacao___13" ~  "Olanzapina",
    medicacao == "medicacao___14" ~  "Quetiapina",
    medicacao == "medicacao___15" ~  "Ramelteon",
    medicacao == "medicacao___16" ~  "Agomelatina",
    medicacao == "medicacao___17" ~  "Anti_histaminicos",
    medicacao == "medicacao___18" ~  "Relaxante_muscular",
    medicacao == "medicacao___19" ~  "Dramin")) |> 
    mutate(classe_medicacao = case_when(
    medicacao == "Alprazolam" ~"Benzodiazepínico",
    medicacao == "Bromazepam" ~"Benzodiazepínico",
    medicacao == "Clonazepam" ~"Benzodiazepínico",
    medicacao == "Diazepam" ~"Benzodiazepínico",
    medicacao == "Zolpidem" ~"Drogas Z",
    medicacao == "Eszopiclona" ~"Drogas Z",
    medicacao == "Amitriptilina" ~"Antidepressivos sedativos",
    medicacao == "Doxepina" ~"Antidepressivos sedativos",
    medicacao == "Trazodona" ~"Antidepressivos sedativos",
    medicacao == "Gabapentina" ~"Anticonvulsivantes",
    medicacao == "Pregabalina" ~ "Anticonvulsivantes",
    medicacao == "Mirtazapina" ~ "Antidepressivos sedativos",
    medicacao == "Olanzapina" ~ "Antipsicóticos",
    medicacao == "Quetiapina" ~ "Antipsicóticos",
    medicacao == "Ramelteon" ~ "Agonista do receptor de melatonina",
    medicacao == "Agomelatina" ~ "Agonista do receptor de melatonina",
    medicacao == "Anti_histaminicos" ~ "Sem Receita",
    medicacao == "Relaxante_muscular" ~ "Sem Receita",
    medicacao == "Dramin" ~ "Sem Receita")) |> 
  filter(!taken == 0)

sum_df <- long_df |> 
  group_by(medicacao) |> 
  summarise(total_taken = sum(taken, na.rm = TRUE)) |> 
  mutate(classe_medicacao = case_when(
    medicacao == "Alprazolam" ~"Benzodiazepínico",
    medicacao == "Bromazepam" ~"Benzodiazepínico",
    medicacao == "Clonazepam" ~"Benzodiazepínico",
    medicacao == "Diazepam" ~"Benzodiazepínico",
    medicacao == "Zolpidem" ~"Drogas Z",
    medicacao == "Eszopiclona" ~"Drogas Z",
    medicacao == "Amitriptilina" ~"Antidepressivos sedativos",
    medicacao == "Doxepina" ~"Antidepressivos sedativos",
    medicacao == "Trazodona" ~"Antidepressivos sedativos",
    medicacao == "Gabapentina" ~"Anticonvulsivantes",
    medicacao == "Pregabalina" ~ "Anticonvulsivantes",
    medicacao == "Mirtazapina" ~ "Antidepressivos sedativos",
    medicacao == "Olanzapina" ~ "Antipsicóticos",
    medicacao == "Quetiapina" ~ "Antipsicóticos",
    medicacao == "Ramelteon" ~ "Agonista do receptor de melatonina",
    medicacao == "Agomelatina" ~ "Agonista do receptor de melatonina",
    medicacao == "Anti_histaminicos" ~ "Sem Receita",
    medicacao == "Relaxante_muscular" ~ "Sem Receita",
    medicacao == "Dramin" ~ "Sem Receita"))|> 
  mutate(across(c("medicacao", "classe_medicacao"), as_factor), 
         medicacao = fct_reorder(medicacao, total_taken))
```

```{r}
#| label: ✅ barras total medicamento (com filtro e sem filtro)

# Filtrando para pegar os 10 medicamentos mais utilizados

bar_meds_filtered <- sum_df |> 
  filter(total_taken > 45) |> 
  ggplot() +
  aes(
    x = medicacao,
    fill = classe_medicacao,
    weight = total_taken
  ) +
  geom_bar() +
  scale_fill_brewer(palette = "Set2", direction = -1) +
  coord_flip() +
  theme_minimal() 

ggplot2::ggsave("img/bar_meds_filtered.png", plot = bar_meds_filtered, width = 10, height = 6, dpi = 300)

bar_meds_filtered

# Versão sem filtro (todos os medicamentos)

bar_meds_unfiltered <- sum_df |> 
  ggplot() +
  aes(
    x = medicacao,
    fill = classe_medicacao,
    weight = total_taken
  ) +
  geom_bar() +
  scale_fill_brewer(palette = "Set2", direction = -1) +
  coord_flip() +
  theme_minimal() 

ggplot2::ggsave("img/bar_meds_unfiltered.png", plot = bar_meds_unfiltered, width = 10, height = 6, dpi = 300)

bar_meds_unfiltered
```

```{r}
#| label: ✅ barras de proporção de uso de medicamentos entre os grupos (ocasional vs contínuo)
#| 
bar_prop <- long_df |>
 ggplot() +
  aes(x = medicacao, fill = medicacao_semana_tr) +
  geom_bar(position = "fill") +
  scale_fill_brewer(palette = "Set2", direction = 1) +
  coord_flip() +
  theme_minimal()

ggplot2::ggsave("img/bar_prop.png", plot = bar_prop, width = 10, height = 6, dpi = 300)

bar_prop
```

```{r}
#| label: barras por classe

bar_class_total <- sum_df |> 
  group_by(classe_medicacao)|>
  summarise(sum(total_taken)) |>
  rename(sum_total_taken = `sum(total_taken)`) |> 
  mutate(classe_medicacao = fct_reorder(classe_medicacao, sum_total_taken)) |> 
    ggplot() +
      aes(
        x = classe_medicacao,
        fill = classe_medicacao,
        weight = sum_total_taken
      ) +
      geom_bar() +
      scale_fill_brewer(palette = "Paired", direction = 1) +
      coord_flip() +
      theme_minimal() 

ggplot2::ggsave("img/bar_class_total.png", plot = bar_class_total, width = 10, height = 6, dpi = 300)

bar_class_total
```

```{r}
bar_prop_class <- long_df |>
 ggplot() +
  aes(x = classe_medicacao, fill = medicacao_semana_tr) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  coord_flip() +
  theme_minimal()

ggplot2::ggsave("img/bar_prop_class.png", plot = bar_prop_class, width = 10, height = 6, dpi = 300)
```

# Tabela de Descritivos

```{r}
#| label: table 1

tbl <- df_insones |> 
  select(medicacao___1, medicacao___2, medicacao___3, medicacao___4, medicacao___5, medicacao___6, medicacao___7, medicacao___8, medicacao___9, medicacao___9, medicacao___12, medicacao___10, starts_with("medicacao___"),
         medicacao_semana_tr,
         idade, 
         sexo_tr,
         atividade_fisica_tr,
         escolaridade_tr, 
         estado_civil_tr, 
         etnia_tr,
         regiao, 
         igi_escore, 
         starts_with("ehad_")) |> 
  tbl_summary(
    by = medicacao_semana_tr,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = all_continuous() ~ 2,
    label = list(escolaridade_tr ~ "Escolaridade",
                 idade ~ "Idade",
                 etnia_tr ~ "Etnia",
                 sexo_tr ~ "Sexo",
                 regiao ~ "Região",
                 estado_civil_tr ~ "Estado Civil",
                 atividade_fisica_tr ~ "Atividade Física",
                 igi_escore ~ "IGI Score",
                 ehad_depressao_escore ~ "Depressão (HADS-D)",
                 ehad_ansiedade_escore ~ "Ansiedade (HADS-A)",
                 medicacao___1 ~ "Alprazolam",
                 medicacao___2 ~  "Bromazepam",
                 medicacao___3 ~ "Clonazepam",
                 medicacao___4 ~ "Diazepam",
                 medicacao___5 ~ "Zolpidem",
                 medicacao___6 ~ "Eszopiclona",
                 medicacao___7 ~ "Amitriptilina",
                 medicacao___8 ~ "Doxepina",
                 medicacao___9 ~ "Trazodona",
                 medicacao___10 ~ "Gabapentina",
                 medicacao___11 ~  "Pregabalina",
                 medicacao___12 ~  "Mirtazapina",
                 medicacao___13 ~  "Olanzapina",
                 medicacao___14 ~  "Quetiapina",
                 medicacao___15 ~  "Ramelteon",
                 medicacao___16 ~  "Agomelatina",
                 medicacao___17 ~  "Anti-histamínicos",
                 medicacao___18 ~  "Relaxante Muscular",
                 medicacao___19 ~  "Dramin"
                 ),
    missing = "no"
  ) |> add_p()

opts <- options(knitr.kable.NA = "")


tbl_tibble <- as_tibble(x = tbl) 
write_csv(x = tbl_tibble, file = "table1.csv", na = "")

tbl
```

```{r}
#| label: table 1 (uso vs não uso) apenas variáveis socio

tbl1 <- df_insones |> 
  select(uso_naouso,
         idade, 
         sexo_tr,
         atividade_fisica_tr,
         escolaridade_tr, 
         estado_civil_tr, 
         etnia_tr,
         regiao, 
         igi_escore, 
         starts_with("ehad_")) |> 
  tbl_summary(
    by = uso_naouso,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} ({p}%)"
    ),
    digits = all_continuous() ~ 2,
    label = list(escolaridade_tr ~ "Escolaridade",
                 idade ~ "Idade",
                 etnia_tr ~ "Etnia",
                 sexo_tr ~ "Sexo",
                 regiao ~ "Região",
                 estado_civil_tr ~ "Estado Civil",
                 atividade_fisica_tr ~ "Atividade Física",
                 igi_escore ~ "IGI Score",
                 ehad_depressao_escore ~ "Depressão (HADS-D)",
                 ehad_ansiedade_escore ~ "Ansiedade (HADS-A)"
                 ),
    missing = "no"
  ) |> add_p()

opts <- options(knitr.kable.NA = "")


tbl_tibble <- as_tibble(x = tbl) 
write_csv(x = tbl_tibble, file = "table_1.csv", na = "")

tbl1
```

```{r}
kable_html <- kable(tbl, "html", align = "lccc") |> 
  pack_rows(index = c("Benzodiazepínico" = 4,
                      "Drogas Z" = 2,
                      "Antidepressivos Sedativos" = 4,
                      "Anticonvulsivantes" = 2,
                      "Antipsicóticos" = 2,
                      "Agonista do receptor de melatonina" = 2,
                      "Over the Counter" = 3
                      )) |> 
  add_indent(positions = c(22, 23, 25, 26, 28, 29, 31, 32, 34, 35, 37:42))

html_file <- "index.html"
writeLines(as.character(kable_html), con = html_file)
pandoc_convert(html_file, to = "docx", output = "table.docx")
```

Regressão Logística

```{r}

#df$medicacao_semana_tr <- fct_relevel(df$randomizacao_tr, c("Uso Contínuo (6-7 dias)", "Uso Ocasional (1-5 dias)"))

logit_model <- glm(medicacao_semana_tr ~ sexo_tr + escolaridade_tr + estado_civil_tr + etnia_tr + atividade_fisica_tr + igi_escore + ehad_ansiedade_escore + ehad_depressao_escore, data = df, family = binomial)

modelsummary(logit_model,
             exponentiate = TRUE,
             stars = c('*' =.05, '**' = .01),
             fmt = 2, 
             estimate = "{estimate}{stars} [{conf.low}, {conf.high}]", statistic = NULL )

levels(df$medicacao_semana_tr)
#  report(logit_model)
```

```{r}
#| label: check model (VD = medicacao_semana_tr)

check_autocorrelation(logit_model)
check_collinearity(logit_model)
check_model(logit_model)
```
